# Generated by Django 5.0.1 on 2024-09-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='village',
            name='subdistrict',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='SubDistrict',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
