# Generated by Django 5.0.1 on 2025-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0004_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
