# Generated by Django 5.0.1 on 2025-06-16 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0006_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('village', 'Village-based'), ('geojson', 'GeoJSON Upload'), ('drawn', 'Drawn Polygons')], default='village', max_length=20)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('village_id', models.IntegerField(blank=True, null=True)),
                ('control_state', models.CharField(blank=True, max_length=100, null=True)),
                ('control_district', models.CharField(blank=True, max_length=100, null=True)),
                ('control_subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('control_village', models.CharField(blank=True, max_length=100, null=True)),
                ('control_village_id', models.IntegerField(blank=True, null=True)),
                ('intervention_start_year', models.IntegerField(blank=True, null=True)),
                ('intervention_end_year', models.IntegerField(blank=True, null=True)),
                ('geojson_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
