# Generated by Django 5.0.1 on 2025-06-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.TextField(blank=True, help_text='Base64 encoded satellite image', null=True),
        ),
    ]
