# Generated by Django 4.2.16 on 2025-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0008_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_skipped',
            field=models.BooleanField(default=False),
        ),
    ]