# Generated by Django 5.0.1 on 2025-07-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0008_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='subdistrict_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='sc_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='st_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='total_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
