# Generated by Django 5.0.1 on 2025-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0009_district_district_id_state_state_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='control_village_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='village_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
