# Generated by Django 5.0.1 on 2025-07-22 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0010_alter_project_control_village_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('village_access_limit', models.IntegerField(blank=True, null=True)),
                ('api_calls_per_day', models.IntegerField(blank=True, null=True)),
                ('data_export_allowed', models.BooleanField(default=True)),
                ('custom_polygon_allowed', models.BooleanField(default=True)),
                ('priority_support', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='has_selected_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Network Admin'), ('superuser', 'Super User')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('villages_accessed_this_month', models.IntegerField(default=0)),
                ('api_calls_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gee_api.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='gee_api_sub_user_id_3c3c6f_idx'), models.Index(fields=['plan', 'status'], name='gee_api_sub_plan_id_e92cad_idx')],
            },
        ),
    ]
