# Generated by Django 5.0.1 on 2025-07-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0011_plan_member_has_selected_plan_member_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='api_calls_per_day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='custom_polygon_allowed',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='data_export_allowed',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='priority_support',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='village_access_limit',
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_api_calls_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_village_views_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Network Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(default='Default plan description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limitations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('api_calls_today', models.IntegerField(default=0)),
                ('village_views_this_month', models.IntegerField(default=0)),
                ('last_api_call_date', models.DateField(blank=True, null=True)),
                ('last_village_view_date', models.DateField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gee_api.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
