# Generated by Django 5.0.1 on 2025-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gee_api', '0009_add_profile_skipped_field'),
        ('gee_api', '0012_alter_plan_options_remove_plan_api_calls_per_day_and_more'),
    ]

    operations = [
    ]
