runtime: python312  # Adjust based on your Python version
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

entrypoint: gunicorn -b :$PORT my_gee_backend.wsgi:application

# NOTE: This file is for Google App Engine deployment
# Current deployment uses AWS EC2 + Docker with env.prod file
# Environment variables are managed through Docker Compose and .env files

# Uncomment and configure these if you plan to use Google App Engine:
# env_variables:
#   SECRET_KEY: "your-secure-django-secret-key"
#   DEBUG: "False"
#   ALLOWED_HOSTS: "yourdomain.com,www.yourdomain.com"
#   DATABASE_NAME: "your-database-name"
#   DATABASE_USER: "your-database-user"
#   DATABASE_PASSWORD: "your-secure-database-password"
#   DATABASE_HOST: "your-database-host.amazonaws.com"
#   DATABASE_PORT: "5432"
#   GOOGLE_EARTH_ENGINE_API_KEY: "your-gee-api-key"
#   GOOGLE_APPLICATION_CREDENTIALS: "path-to-your-service-account.json"
#   GOOGLE_OAUTH2_CLIENT_ID: "your-google-oauth-client-id"
#   GOOGLE_OAUTH2_CLIENT_SECRET: "your-google-oauth-client-secret"
#   CORS_ALLOWED_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"
  

handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: auto
