runtime: python312  # Adjust based on your Python version
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

entrypoint: gunicorn -b :$PORT my_gee_backend.wsgi:application

env_variables:
  DJANGO_SECRET_KEY: "your-secure-django-secret-key-here"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "yourdomain.com, www.yourdomain.com"  # Fill in with your actual domain
  DATABASE_NAME: "my_django_db"
  DATABASE_USER: "django_user"
  DATABASE_PASSWORD: "your-secure-database-password"
  DATABASE_HOST: "your-database-host.amazonaws.com"  # Your actual database host
  DATABASE_PORT: "5432"
  GOOGLE_EARTH_ENGINE_API_KEY: "your-gee-api-key"
  GOOGLE_APPLICATION_CREDENTIALS: "path-to-your-service-account-json"  # Path to your service account JSON
  CORS_ORIGIN_WHITELIST: "http://localhost:5173"
  

handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: auto
