# Generated by Django 4.2.16 on 2025-11-27 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricCatalog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='ID from the source file', max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='continuous_monitoring.cmproject')),
            ],
            options={
                'unique_together': {('project', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RawDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cm_uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('ANALYZED', 'Analyzed (Waiting Confirmation)'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='continuous_monitoring.cmproject')),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedTimeSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='continuous_monitoring.metriccatalog')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='continuous_monitoring.unifiedobject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='continuous_monitoring.cmproject')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'object', 'timestamp'], name='continuous__project_69079a_idx'), models.Index(fields=['project', 'metric', 'timestamp'], name='continuous__project_3c4e72_idx')],
            },
        ),
    ]
