# Generated by Django 4.2.16 on 2025-11-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedobject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_objects', to='continuous_monitoring.cmproject'),
        ),
    ]
